import { BusFront, CheckCircle2, FileBadge, IdCard, LockKeyhole, Mail, Phone, ShieldCheck, UserRound } from 'lucide-react';
import { useAuth } from '../../auth/AuthContext';
import { StaffPageHeading } from '../../components/staff/StaffUI';
import { useDriverOperations } from '../../operations/OperationsContext';
export function DriverProfilePage() {
    const { user } = useAuth();
    const { activeTrip } = useDriverOperations();
    const employeeCode = user?.id?.replace('drv-', 'DRV-').toUpperCase() ?? 'DRV-ASSIGNED';
    return <div><StaffPageHeading eyebrow="Driver account" title="Profile" description="Your identity, assignment and safety credentials."/><div className="staff-profile-grid"><section className="staff-profile-card"><div className="staff-profile-identity"><span>{user?.initials ?? 'DR'}</span><div><h2>{user?.name ?? 'Driver'}</h2><p>University transport driver</p><span className="staff-record-status staff-record-status--completed"><CheckCircle2 /> Active</span></div></div><div className="staff-profile-fields"><div><IdCard /><span><small>Employee ID</small><strong>{employeeCode}</strong></span></div><div><FileBadge /><span><small>Driving licence</small><strong>Verified by transport office</strong></span></div><div><Phone /><span><small>Phone</small><strong>{activeTrip.driver.phone}</strong></span></div><div><Mail /><span><small>Email</small><strong>{user?.email}</strong></span></div></div></section><aside><section className="staff-profile-card"><h3>Current assignment</h3><div className="staff-profile-assignment"><BusFront /><span><small>Assigned bus</small><strong>{activeTrip.registration}</strong><em>Bus {activeTrip.busNumber}</em></span></div><div className="staff-profile-assignment"><UserRound /><span><small>Assigned conductor</small><strong>{activeTrip.conductor.name}</strong><em>{activeTrip.conductor.phone}</em></span></div></section><section className="staff-privacy-card"><ShieldCheck /><div><strong>Location privacy</strong><p>Your location is shared only while a trip is active and stops automatically when you end it.</p></div></section><section className="staff-profile-card staff-account-link"><LockKeyhole /><span><strong>Account security</strong><small>Change password and review sessions</small></span></section></aside></div></div>;
}
