import { BusFront, CheckCircle2, IdCard, Mail, Phone, Route, ShieldCheck, UserRound } from 'lucide-react';
import { useAuth } from '../../auth/AuthContext';
import { StaffPageHeading } from '../../components/staff/StaffUI';
import { useConductorOperations } from '../../operations/OperationsContext';
export function ConductorProfilePage() {
    const { user } = useAuth();
    const { activeTrip } = useConductorOperations();
    const employeeCode = user?.id?.replace('con-', 'CON-').toUpperCase() ?? 'CON-ASSIGNED';
    return <div><StaffPageHeading eyebrow="Conductor account" title="Profile" description="Your identity and current transport assignment."/><div className="staff-profile-grid"><section className="staff-profile-card"><div className="staff-profile-identity"><span>{user?.initials ?? 'CO'}</span><div><h2>{user?.name ?? 'Conductor'}</h2><p>University transport conductor</p><span className="staff-record-status staff-record-status--completed"><CheckCircle2 /> Active</span></div></div><div className="staff-profile-fields"><div><IdCard /><span><small>Employee ID</small><strong>{employeeCode}</strong></span></div><div><Phone /><span><small>Phone</small><strong>{activeTrip.conductor.phone}</strong></span></div><div><Mail /><span><small>Email</small><strong>{user?.email}</strong></span></div><div><ShieldCheck /><span><small>Duty status</small><strong>On duty</strong></span></div></div></section><aside><section className="staff-profile-card"><h3>Current assignment</h3><div className="staff-profile-assignment"><BusFront /><span><small>Assigned bus</small><strong>{activeTrip.registration}</strong><em>Bus {activeTrip.busNumber} · {activeTrip.capacity} seats</em></span></div><div className="staff-profile-assignment"><Route /><span><small>Assigned route</small><strong>{activeTrip.routeCode}</strong><em>{activeTrip.routeName}</em></span></div><div className="staff-profile-assignment"><UserRound /><span><small>Assigned driver</small><strong>{activeTrip.driver.name}</strong><em>{activeTrip.driver.phone}</em></span></div></section><section className="staff-privacy-card"><ShieldCheck /><div><strong>Passenger data</strong><p>Only trip totals are recorded. SmartTransit does not identify individual passengers in seat updates.</p></div></section></aside></div></div>;
}
