import { defaultStudentRoute, getRouteServiceLabel, indusRoutes } from "./indusRoutes.js";

const [route1, route2, route3, route4, route5, route6, route7] = indusRoutes;
const selectedStop = route4.stops.find((stop) => stop.name === "Shilaj Circle");

export const initialStudentNotifications = [
    {
        id: "notif-1",
        type: "delay",
        title: `Traffic near ${selectedStop.name}`,
        message: "Your bus may be delayed by approximately 10 minutes.",
        createdAt: "2 min ago",
        unread: true,
        routeCode: defaultStudentRoute.code,
    },
    {
        id: "notif-2",
        type: "route-change",
        title: `Route ${defaultStudentRoute.code} pickup note`,
        message: `${selectedStop.name} pickup is operating from the regular marked point today.`,
        createdAt: "Yesterday, 7:00 PM",
        unread: true,
        routeCode: defaultStudentRoute.code,
    },
    {
        id: "notif-3",
        type: "general",
        title: "Transport help desk",
        message: "The campus transport office is available from 8 AM to 5 PM.",
        createdAt: "18 Aug, 10:30 AM",
        unread: false,
    },
    {
        id: "notif-4",
        type: "cancellation",
        title: `Route ${route7.code} evening trip cancelled`,
        message: `The evening service on Route ${route7.code} is cancelled due to maintenance.`,
        createdAt: "16 Aug, 4:15 PM",
        unread: false,
        routeCode: route7.code,
    },
];

export const initialNotificationCampaigns = [
    {
        id: "NTF-2026-0182",
        type: "delay",
        title: `Delay on Route ${route5.code}`,
        message: `Bus ${route5.primaryBusNumber} is running approximately 14 minutes late near Anjali Crossroad.`,
        audience: "route",
        routeCode: route5.code,
        deliveryMode: "now",
        createdAt: "Today, 8:02 AM",
        status: "delivered",
        deliveredCount: route5.studentCount,
        recipientCount: route5.studentCount,
        createdBy: "Admin Operator",
    },
    {
        id: "NTF-2026-0181",
        type: "route-change",
        title: `Route ${route3.code} stop updated`,
        message: "The Science City pickup point will use the main road shelter tomorrow morning.",
        audience: "route",
        routeCode: route3.code,
        deliveryMode: "now",
        createdAt: "20 Aug, 7:00 PM",
        status: "delivered",
        deliveredCount: route3.studentCount - 2,
        recipientCount: route3.studentCount,
        createdBy: "Operations Manager",
    },
    {
        id: "NTF-2026-0180",
        type: "general",
        title: "Evening service reminder",
        message: "Evening buses will depart from the Indus University main gate.",
        audience: "all",
        deliveryMode: "scheduled",
        scheduledFor: "22 Aug 2026, 4:00 PM",
        createdAt: "20 Aug, 4:00 PM",
        status: "scheduled",
        deliveredCount: 0,
        recipientCount: indusRoutes.reduce((sum, route) => sum + route.studentCount, 0),
        createdBy: "Admin Operator",
    },
    {
        id: "NTF-2026-0179",
        type: "cancellation",
        title: `Route ${route7.code} service cancelled`,
        message: "The afternoon service is cancelled because the assigned bus is under maintenance.",
        audience: "route",
        routeCode: route7.code,
        deliveryMode: "now",
        createdAt: "19 Aug, 1:20 PM",
        status: "failed",
        deliveredCount: 0,
        recipientCount: route7.studentCount,
        createdBy: "Admin Operator",
    },
];

export const initialComplaintCases = [
    {
        id: "CMP-2026-0445",
        studentId: "stu-2023",
        studentName: "Aarav Shah",
        studentEmail: "student@iite.indusuni.ac.in",
        category: "Delay",
        subject: "Pickup time mismatch",
        description: `The displayed pickup time was ${selectedStop.scheduledTime}, but the bus arrived after 8:30 AM without an alert.`,
        relatedService: getRouteServiceLabel(route4),
        routeCode: route4.code,
        busNumber: route4.primaryBusNumber,
        tripId: "TRIP-2108-IU-R4-AM",
        status: "new",
        assignedTo: "Unassigned",
        createdAt: "21 Aug 2026, 4:15 PM",
        updatedAt: "21 Aug 2026, 4:15 PM",
        timeline: [
            {
                id: "evt-445-1",
                title: "Complaint submitted",
                detail: "Student reported a pickup-time mismatch.",
                timestamp: "21 Aug, 4:15 PM",
            },
        ],
        internalNotes: [],
    },
    {
        id: "CMP-2026-0442",
        studentId: "stu-2023",
        studentName: "Aarav Shah",
        studentEmail: "student@iite.indusuni.ac.in",
        category: "Bus condition",
        subject: "Air conditioning needs attention",
        description: "Cooling was inconsistent during the afternoon trip and the rear section became uncomfortable.",
        relatedService: getRouteServiceLabel(route4),
        routeCode: route4.code,
        busNumber: route4.primaryBusNumber,
        tripId: "TRIP-1808-IU-R4-PM",
        status: "in-progress",
        assignedTo: "Fleet Maintenance",
        createdAt: "18 Aug 2026, 9:20 AM",
        updatedAt: "19 Aug 2026, 11:05 AM",
        timeline: [
            {
                id: "evt-442-1",
                title: "Complaint submitted",
                detail: "Bus condition issue reported.",
                timestamp: "18 Aug, 9:20 AM",
            },
            {
                id: "evt-442-2",
                title: "Assigned for review",
                detail: "Assigned to Fleet Maintenance.",
                timestamp: "19 Aug, 11:05 AM",
            },
        ],
        internalNotes: [
            {
                id: "note-442-1",
                author: "Operations Manager",
                message: "Inspect AC unit after the afternoon return trip.",
                createdAt: "19 Aug, 11:05 AM",
            },
        ],
    },
    {
        id: "CMP-2026-0438",
        studentId: "stu-2058",
        studentName: "Diya Patel",
        studentEmail: "diya.patel@iite.indusuni.ac.in",
        category: "Route or stop",
        subject: "Driver skipped designated stop",
        description: "The bus passed the marked pickup point even though students were waiting near the shelter.",
        relatedService: getRouteServiceLabel(route2),
        routeCode: route2.code,
        busNumber: route2.primaryBusNumber,
        tripId: "TRIP-1808-IU-R2-AM",
        status: "in-progress",
        assignedTo: "Route Supervisor",
        createdAt: "18 Aug 2026, 8:14 AM",
        updatedAt: "18 Aug 2026, 10:40 AM",
        timeline: [
            {
                id: "evt-438-1",
                title: "Complaint submitted",
                detail: "Missed-stop issue reported.",
                timestamp: "18 Aug, 8:14 AM",
            },
            {
                id: "evt-438-2",
                title: "Investigation started",
                detail: "GPS trace shared with Route Supervisor.",
                timestamp: "18 Aug, 10:40 AM",
            },
        ],
        internalNotes: [],
    },
    {
        id: "CMP-2026-0412",
        studentId: "stu-2023",
        studentName: "Aarav Shah",
        studentEmail: "student@iite.indusuni.ac.in",
        category: "Delay",
        subject: "Morning bus arrived late",
        description: `The bus reached ${selectedStop.name} around 15 minutes after the displayed time.`,
        relatedService: getRouteServiceLabel(route4),
        routeCode: route4.code,
        busNumber: route4.primaryBusNumber,
        tripId: "TRIP-1208-IU-R4-AM",
        status: "resolved",
        assignedTo: "Operations Team",
        createdAt: "12 Aug 2026, 8:50 AM",
        updatedAt: "14 Aug 2026, 3:10 PM",
        resolution: "Traffic congestion was confirmed. The trip schedule has been adjusted by five minutes.",
        timeline: [
            {
                id: "evt-412-1",
                title: "Complaint submitted",
                detail: "Morning delay reported.",
                timestamp: "12 Aug, 8:50 AM",
            },
            {
                id: "evt-412-2",
                title: "Review completed",
                detail: "GPS and traffic data reviewed.",
                timestamp: "13 Aug, 2:30 PM",
            },
            {
                id: "evt-412-3",
                title: "Resolved",
                detail: "Resolution sent to the student.",
                timestamp: "14 Aug, 3:10 PM",
            },
        ],
        internalNotes: [
            {
                id: "note-412-1",
                author: "Admin Operator",
                message: `Recurring traffic confirmed near ${selectedStop.name}.`,
                createdAt: "13 Aug, 2:30 PM",
            },
        ],
    },
];

export const communicationRoutes = [route1, route2, route3, route4, route5, route6, route7];
